# Generated by Django 6.0.1 on 2026-01-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("drink", "水を飲んだ"),
                            ("outside", "外へ出た"),
                            ("stroll", "散歩をした"),
                            ("stretch", "ストレッチをした"),
                            ("gym", "ジムへ行った"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_done", models.BooleanField(default=False)),
            ],
        ),
    ]
