# Generated by Django 5.2.10 on 2026-02-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_dailystamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystamp',
            name='last_skipped_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
