# Generated by Django 5.2.10 on 2026-02-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_title_activity_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystamp',
            name='done_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystamp',
            name='skipped_days',
            field=models.IntegerField(default=0),
        ),
    ]
