# Generated by Django 5.2.10 on 2026-02-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_dailystamp_done_days_dailystamp_skipped_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystamp',
            name='growth_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystamp',
            name='growth_stage',
            field=models.IntegerField(default=0),
        ),
    ]
