# Generated by Django 5.2.10 on 2026-02-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_idea'),
        ('activities', '0006_dailystamp_growth_count_dailystamp_growth_stage'),
    ]

    operations = [
    ]
