# Generated by Django 6.0.2 on 2026-02-04 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_merge_20260204_0234"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="heart",
            field=models.ManyToManyField(
                blank=True, related_name="heart_ideas", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="idea_images/"),
        ),
        migrations.AddField(
            model_name="idea",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_ideas", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="thumbs_up",
            field=models.ManyToManyField(
                blank=True, related_name="thumbs_up_ideas", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="IdeaComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="activities.idea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
