# Generated by Django 6.0.2 on 2026-02-04 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0008_idea_heart_idea_image_idea_likes_idea_thumbs_up_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="heart",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="thumbs_up",
        ),
        migrations.CreateModel(
            name="IdeaReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("heart", "♡"), ("like", "👍"), ("sad", "😢")],
                        max_length=10,
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="activities.idea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="IdeaComment",
        ),
    ]
